// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'is-active': string;
  'is-inline': string;
  'is-navigation-menu': string;
  'sub-nav': string;
  'sub-nav__item': string;
  'u-link-background-hover-color-1': string;
  'u-link-background-hover-color-2': string;
  'u-link-background-hover-color-3': string;
  'u-link-background-hover-color-4': string;
  'u-link-background-hover-dark': string;
  'u-link-background-hover-light': string;
  'u-link-hover-color-1': string;
  'u-link-hover-color-2': string;
  'u-link-hover-color-3': string;
  'u-link-hover-color-4': string;
  'u-link-hover-dark': string;
  'u-link-hover-light': string;
}
export const cssExports: CssExports;
export default cssExports;
