// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'excerpt': string;
  'excerpt__btn': string;
  'excerpt__content': string;
  'excerpt__content-inside': string;
  'excerpt__image': string;
  'excerpt__time': string;
  'is-archive': string;
  'is-component': string;
}
export const cssExports: CssExports;
export default cssExports;
