// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'song-kick': string;
  'song-kick__artist': string;
  'song-kick__content': string;
}
export const cssExports: CssExports;
export default cssExports;
