// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'faqs': string;
  'faqs__caption': string;
  'faqs__content': string;
  'faqs__item': string;
  'faqs__reveal': string;
  'faqs__trigger': string;
  'is-visible': string;
}
export const cssExports: CssExports;
export default cssExports;
