// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animated-banner': string;
  'animated-banner__col': string;
  'animated-banner__decal': string;
  'animated-banner__image': string;
  'animated-banner__title': string;
  'animated-banner__title-inside': string;
  'kf-col': string;
  'kf-decal': string;
  'kf-image': string;
}
export const cssExports: CssExports;
export default cssExports;
