// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hero': string;
  'hero__image': string;
  'hero__row': string;
  'hero__title': string;
  'hero__title-inside': string;
}
export const cssExports: CssExports;
export default cssExports;
