// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'music': string;
  'music__logos': string;
  'music__logos-image': string;
  'music__player': string;
  'music__row': string;
}
export const cssExports: CssExports;
export default cssExports;
