// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'post-nav__nav': string;
  'post-nav__nav-link': string;
}
export const cssExports: CssExports;
export default cssExports;
