// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'is-left': string;
  'is-right': string;
  'logos': string;
  'logos__carousel': string;
  'logos__nav': string;
  'logos__slide': string;
  'logos__slide-inside': string;
  'logos__trigger': string;
}
export const cssExports: CssExports;
export default cssExports;
