// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'quote': string;
  'quote__carousel': string;
  'quote__pagination': string;
  'quote__profile': string;
  'quote__profile-image': string;
}
export const cssExports: CssExports;
export default cssExports;
