// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cta': string;
  'cta__link': string;
  'header': string;
  'header__logo': string;
  'is-hidden': string;
}
export const cssExports: CssExports;
export default cssExports;
