// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'social': string;
  'social__link': string;
}
export const cssExports: CssExports;
export default cssExports;
