// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content-image__container': string;
  'content-image__content': string;
  'content-image__figure': string;
  'content-image__row': string;
  'is-left': string;
  'is-right': string;
}
export const cssExports: CssExports;
export default cssExports;
